#### Loading the data

In [1]:
import pickle as pkl

In [2]:
file = open('model.pkl','rb')
model = pkl.load(file)
file.close()

In [3]:
file = open('label.pkl','rb')
label = pkl.load(file)
file.close()

file = open('industry_onehot.pkl','rb')
industry_onehot = pkl.load(file)
file.close()

file = open('minmax.pkl','rb')
minmax = pkl.load(file)
file.close()

#### Inserting random values for testing purpose

In [4]:
Gender = 1
Age = 30
Debt = 5
Married = 1
BankCustomer = 1
Industry = 'Industrials'
YearsEmployed = 3
PriorDefault = 1
Employed = 0
CreditScore = 5
DriversLicense = 0
Income = 500
Approved = 1

In [5]:
Industry = industry_onehot.transform([label.transform([Industry])]).toarray()

In [6]:
Industry

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [7]:
import numpy as np

In [8]:
test_data = np.array([[Gender,Age,Debt,Married,BankCustomer,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Income]])

In [9]:
test_data

array([[  1,  30,   5,   1,   1,   3,   1,   0,   5,   0, 500]])

In [10]:
test_X = np.c_[test_data,Industry]

In [11]:
test_X

array([[  1.,  30.,   5.,   1.,   1.,   3.,   1.,   0.,   5.,   0., 500.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.]])

In [12]:
test_X = minmax.transform(test_X)

In [13]:
model.predict(test_X)

array([1], dtype=int64)